# Generated by Django 6.0.6 on 2026-06-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
