# Generated by Django 6.0.6 on 2026-06-09 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_device_is_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='temperaturedata',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='temperaturedata',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
